#!/bin/bash

FLAGS="-g -std=c23 -Wall -Werror -Wno-unused-variable -Wno-unused-function -Wno-unused-but-set-variable -Wno-missing-braces"
INCLUDE="-I$VULKAN_SDK/include -I."
LIB="-L$VULKAN_SDK/lib -lvulkan -lm -lX11 -lXi"
SRC="linux_main.c"
mkdir -p bin
FILENAME="bin/a"

glslc shader.vert -o vertex.spv
glslc shader.frag -o fragment.spv
clang -o $FILENAME $FLAGS $SRC $INCLUDE $LIB $1

#fix tags
cat ~/.cache/vulkan.tags > tags
ctags -R -a .
