#!/bin/bash

FLAGS="-g -std=c23 -Wall -Werror"
INCLUDE="-I$VULKAN_SDK/include -I."
LIB="-L$VULKAN_SDK/lib -lvulkan -lX11"
SRC="game.c"
FILENAME="bin/game"

clang-21 -o $FILENAME $FLAGS $SRC $INCLUDE $LIB $1

#fix tags
cat ~/.cache/vulkan.tags > tags
ctags -R -a .
